# -*- coding: utf-8 -*-
"""Syllabus_organizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TuR_M-sjCfDdPX-micAGoM28VCydJiV
"""

!pip install python-docx

from docx import Document
from docx.oxml.ns import qn
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from google.colab import files

print("Please upload your syllabus Markdown file (e.g., syllabus.md):")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
input_text = uploaded[filename].decode('utf-8')

print("First 100 characters of the file:", repr(input_text[:100]))

lines = input_text.split('\n')

print("First 5 lines after split:", lines[:5])

print("Creating document...")
doc = Document()

current_subject = None
current_unit = None
skip_section = False

for line in lines:
    line = line.strip()
    if any(line.startswith(x) for x in ("Text Books:", "Reference Books:", "Online Resources:", "Course Outcomes:", "2018-2019")):
        skip_section = True
        continue
    elif skip_section and not line.isupper() and not line.startswith("UNIT"):
        continue
    else:
        skip_section = False
    if (line.isupper() and "UNIT" not in line and not line.startswith(("IV YEAR", "L T P C", "3--", "COMPUTER SCIENCE AND ENGINEERING"))):
        current_subject = doc.add_paragraph(line)
        current_subject.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        if current_subject.runs:
            current_subject.runs[0].bold = True
        current_unit = None
    elif line.startswith("UNIT"):
        current_unit = doc.add_paragraph(line.split('(~')[0].strip())
        if current_unit.runs:
            current_unit.runs[0].bold = True
    elif current_unit and line and not line.startswith(("IV Year", "Course Code", "L T P C", "3--", "(Common", "Prerequisites", "Course Objectives")):
        if ':' in line:
            subheading = doc.add_paragraph(line)
            if subheading.runs:
                subheading.runs[0].italic = True
        else:
            doc.add_paragraph(line)

output_filename = "Syllabus_IV_Year_BTech_CSE_II_Semester.docx"
doc.save(output_filename)
print(f"Document saved as {output_filename}")

files.download(output_filename)

